config/routes.rb
Rails.application.routes.draw do
  get 'user/show'
  resources :announcements, only: [:index, :show, :new, :create]
  resources :seen_announcements, only: [:create, :update]
  devise_for :users
  root "splash#home"
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :user

  has_many :seen_announcements
  has_many :users, through: :seen_announcements

  validates :content, length: { maximum: 140 }, presence: true

  def custom_time
    if (Time.current - self.created_at) < 1.hour
      "#{((Time.current - self.created_at)/60).round}min" 
    elsif (Time.current - self.created_at) >= 1.hour && (Time.current - self.created_at) < 24.hour
      "#{((Time.current - self.created_at)/3600).round}h" 
    else
      self.created_at.strftime("%d-%m-%y")
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/seen_announcement.rb
class SeenAnnouncement < ApplicationRecord
  belongs_to :user
  belongs_to :announcement

  attribute :seen, :boolean, default: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :announcements

  has_many :seen_announcements
  has_many :announcements, through: :seen_announcements

  def full_name
    "#{name} #{last_name}"
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  def index
    @announcements = Announcement.where("created_at >= ?", 1.day.ago).order(created_at: :desc)
    # @announcements = Announcement.all.order(created_at: :desc)
  end

  def show
    @announcement = Announcement.find(params[:id])

    @seen_announcement = current_user.seen_announcements.find_by(announcement_id: @announcement.id)
    @seen_announcement ||= SeenAnnouncement.new
  end

  def new
    @announcement = Announcement.new
  end

  def create
    @announcement = Announcement.new(announcement_params)
    if @announcement.save
      flash[:notice] = "Announcement successfully created."
      redirect_to announcements_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def announcement_params
    params.require(:announcement).permit(:content).with_defaults(user_id: current_user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:home]

  protected

  def after_sign_in_path_for(resource)
    announcements_path
  end

  # def after_sign_up_path_for(resource)
  #   announcements_path
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :last_name])
  end
end

app/controllers/seen_announcements_controller.rb
class SeenAnnouncementsController < ApplicationController
  def create
    @seen_announcement = SeenAnnouncement.new(seen_announcement_params)
    if @seen_announcement.save
      redirect_to announcements_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @seen_announcement = current_user.seen_announcements.find_by(announcement_id: params[:seen_announcement][:announcement_id])
    if @seen_announcement.update(seen_announcement_params)
      redirect_to announcements_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def seen_announcement_params
    params.require(:seen_announcement).permit(:seen, :announcement_id).with_defaults(user_id: current_user.id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def home
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def set_background_color(announcement)
    seen_announcement=current_user.seen_announcements.find_by(announcement_id: announcement.id)
    if seen_announcement
      if seen_announcement.seen
        background_color = "" 
      else
        background_color = "bg-info" 
      end
    else
      background_color = "bg-info"
    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seen_announcements_helper.rb
module SeenAnnouncementsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/announcements/_announcement.html.erb
<div class="announcement container py-3 border border-secondary border-opacity-25 <%= set_background_color(announcement) %> d-flex flex-row justify-content-between">
  <div>
    <div class="d-flex gap-3">
      <p class="fw-bold m-0"><%= User.find(announcement.user_id).full_name %></p>
      <p class="text-secondary m-0"><%= announcement.custom_time %></p>
    </div>
    <p class="m-0"><%= announcement.content %></p>
  </div>

  <% seen_announcement = current_user.seen_announcements.find_by(announcement_id: announcement.id) %>
  <% seen_announcement ||= SeenAnnouncement.new %>
  <%= form_with model: seen_announcement do |f| %>
    <div>
      <%= f.hidden_field :announcement_id, value: announcement.id %>
    </div>

    <div>
      <%= f.label :seen? %>
      <%= f.check_box :seen, onchange: "this.form.submit()", class: "form-check-input" %>
    </div>
  <% end %>
</div>

app/views/announcements/index.html.erb
<h1>Announcements</h1>
<%= render @announcements %>

app/views/announcements/new.html.erb
<%= form_with model: @announcement do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.text_field :content, class: "form-control", placeholder: "Start writing something great..." %>
  </div>

  <div>
    <%= f.submit "Save", class: "btn btn-primary mt-3" %>
  </div>

<% end %>

app/views/announcements/show.html.erb
<h1>Announcement</h1>
<%= @announcement.content %>

<%= form_with model: @seen_announcement do |f| %>
  <% if @seen_announcement.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @seen_announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.hidden_field :announcement_id, value: @announcement.id %>
  </div>

  <div>
    <%= f.label :seen? %>
    <%= f.check_box :seen, onchange: "this.form.submit()" %>
  </div>

  <div>
    <%= f.submit "Save", class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-sm navbar-dark bg-primary">
  <div class="container">
    <% if user_signed_in? %>
      <%= link_to 'Proyecto 2', announcements_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <nav class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "New Announcement", new_announcement_path, class: "nav-link text-white" %></li>
          <li class="nav-item"><%= link_to "Profile", user_show_path, class: "nav-link text-white" %></li>
          <li class="nav-item"><%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-outline-light' %></li>
        </ul>
      </nav>
    <% else %>
      <%= link_to 'Proyecto 2', root_path, class: "navbar-brand" %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="container">
      <% flash.each do |message_type, message| %>
        <% if message_type == 'notice' %>
          <div class="alert alert-success"><%= message %></div>
        <% else %>
          <div class="alert alert-danger"><%= message %></div>
        <% end %>
      <% end %>
      <%= yield %>
      <%#= debug(params) if Rails.env.development? %>
    </main>
  </body>
</html>

app/views/splash/home.html.erb
<h1 class="display-1 text-center">Proyecto 2</h1>
<ul class="registration-buttons text-center list-unstyled">
  <li><%= link_to 'LOG IN', new_user_session_path, class: 'btn btn-primary w-75 mb-3 mt-5' %></li> 
  <li><%= link_to 'SIGN UP', new_user_registration_path, class: 'btn btn-secondary w-75' %></li> 
</ul>

app/views/user/show.html.erb
<h1>Profile</h1>
<div>
  <p><span class="fw-semibold">Name:</span> <%= current_user.name %></p>
  <p><span class="fw-semibold">Last name:</span> <%= current_user.last_name %></p>
</div>
<%#= link_to "Edit", edit_user_registration_path, class: "nav-link" %>